---  # roles/ec2/tasks/main.yml

- name: Create Webserver Instance
  ec2:
    key_name: aviaws2018
    group_id: "{{ main_sg_id }}"
    instance_type: t2.micro
    image: ami-02e98f78
    region: "{{ aws_region }}"
    instance_tags: {"Name":"Webserver"}
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 10
    vpc_subnet_id: "{{ public_subnet_id }}"
    assign_public_ip: yes
    exact_count: 1
    count_tag:
      Name: webserver
  register: my_web_ec2

#- debug: var=my_web_ec2

- name:  Set EC2 ID in variable
  set_fact:
    ec2_id: "{{ my_web_ec2.instance_ids[0] }}"

- debug: var=ec2_id

- name: Assign EIP to EC2
  ec2_eip:
    device_id: "{{ ec2_id }}"
    public_ip: "{{ my_eip }}"
    region: "{{ aws_region }}"
    allow_reassociation: yes

- name: Create Appserver Instance
  ec2:
    key_name: aviaws2018
    group_id: "{{ private_sg_id }}"
    instance_type: t2.micro
    image: ami-02e98f78
    region: "{{ aws_region }}"
    instance_tags: {"Name":"Appserver"}
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 10
    vpc_subnet_id: "{{ private_subnet_id }}"
    private_ip: "{{ app_private_ip }}"
    exact_count: 1
    count_tag:
      Name: appserver
  register: my_app_ec2
